import os

SECRET_KEY = os.getenv('SUPERSET_SECRET_KEY')
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')

ROW_LIMIT = 50000
WEBSERVER_TIMEOUT = 300
SUPERSET_LOAD_EXAMPLES = False

CACHE_CONFIG = {
    'CACHE_TYPE': 'SimpleCache',
    'CACHE_DEFAULT_TIMEOUT': 300
}

SESSION_COOKIE_SECURE = False
